version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build: .
    # working_dir: /code
    image: web
    command: bash test.sh
    # volumes:
    #   - .:/code
    ports:
      - "4000:4000"
    depends_on:
      - db
    links:
      - db
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - web
    links:
      - db
    volumes:
      - ./config:/code/config
      - ./lib:/code/lib
      - ./priv:/code/priv
      - ./test:/code/test
      - ./web:/code/web
